chore(build): 🔨 add hook rebase logic (#124)
* chore(build): :hammer: test rebase check

* chore(build): :hammer: test rebase check

chore(build): :hammer: test rebase check

chore(build): :hammer: test rebase check

chore(build): :hammer: test rebase check

chore(build): :hammer: test rebase check

chore(build): :hammer: test rebase check

chore(build): :hammer: test rebase check

chore(build): :hammer: test rebase check

* fix(build): :bug: hook rebase logic

* fix(build): :bug: hook rebase logic

* fix(build): :bug: hook rebase logic

* fix(build): :bug: hook rebase logic

* test

fix(build): :bug: hook rebase logic

* chore(conf): :hammer: add kodiak to codeowners for dep merge

* chore(conf): :hammer: add kodiak to codeowners for dep merge

* build(conf): :package: bots cant be codeowners

* chore(deps): :hammer: update renovate conf

diff --git a/.husky/prepare-commit-msg b/.husky/prepare-commit-msg
--- a/.husky/prepare-commit-msg
+++ b/.husky/prepare-commit-msg
@@ -2,11 +2,22 @@
 . "$(dirname -- "$0")/_/husky.sh"
 . "$(dirname "$0")/common.sh"
 
-TMP_FILE=$(git rev-parse --path-format=relative --git-dir)/commit-skip
+REBASE="$(git rev-parse --path-format=relative --git-dir)/rebase-*"
 
-if [ -f $TMP_FILE ]; then
-	echo 'Skipping Commitizen step'
-	exit 0
-fi
+
+lint() {
+ trap 'exit $?' EXIT
+ npx commitlint --edit $1 > /dev/tty
+}
+# if [ -d $REBASE ]; then
+	# echo 'Rebase in progress - Checking Commitlint'
+	if $(lint $1)
+	then
+		echo "Commitlint passed!"
+		exit 0
+	else
+		echo "Commitlint failed - Routing to Commitizen"
+	fi 
+# fi
 
 exec < /dev/tty && npx czg --hook || true
